{{- if include "hearth.hasSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hearth.fullname" . }}
  labels:
    {{- include "hearth.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.tlsCert }}
  tls.crt: {{ .Values.secret.tlsCert | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret.tlsKey }}
  tls.key: {{ .Values.secret.tlsKey | b64enc | quote }}
  {{- end }}
  {{- range $key, $val := .Values.secret.env }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
