//! Generated protobuf types and serde implementations.
//!
//! This module re-exports the types generated by `prost-build` and `pbjson-build`
//! from the `.proto` files in `proto/`. These types are the canonical wire format
//! for all API contracts (ARCHITECTURE.md s4.1).
//!
//! Clippy lints are suppressed for generated code that we cannot control.

/// Identity and realm types.
pub mod identity {
    /// Version 1 of the identity API.
    #[allow(
        clippy::needless_lifetimes,
        clippy::return_self_not_must_use,
        clippy::too_many_lines,
        clippy::manual_let_else,
        clippy::match_single_binding,
        clippy::elidable_lifetime_names,
        clippy::doc_markdown,
        mismatched_lifetime_syntaxes
    )]
    pub mod v1 {
        include!("generated/hearth.identity.v1.rs");
        include!("generated/hearth.identity.v1.serde.rs");
    }
}

/// Claims-based RBAC admin types.
pub mod rbac {
    /// Version 1 of the RBAC admin API.
    #[allow(
        clippy::needless_lifetimes,
        clippy::return_self_not_must_use,
        clippy::too_many_lines,
        clippy::manual_let_else,
        clippy::match_single_binding,
        clippy::elidable_lifetime_names,
        clippy::doc_markdown,
        mismatched_lifetime_syntaxes
    )]
    pub mod v1 {
        include!("generated/hearth.rbac.v1.rs");
        include!("generated/hearth.rbac.v1.serde.rs");
    }
}

/// Audit event types.
pub mod events {
    /// Version 1 of the events API.
    #[allow(
        clippy::needless_lifetimes,
        clippy::return_self_not_must_use,
        clippy::too_many_lines,
        clippy::manual_let_else,
        clippy::match_single_binding,
        clippy::elidable_lifetime_names,
        clippy::doc_markdown,
        mismatched_lifetime_syntaxes
    )]
    pub mod v1 {
        include!("generated/hearth.events.v1.rs");
        include!("generated/hearth.events.v1.serde.rs");
    }
}
